language: java

matrix:
  include:
  - jdk: oraclejdk8
  - name: "Flowable 5 tests"
    jdk: oraclejdk8
    install: true
    script:
      cd scripts && ./run-flowable5-tests.sh
  - jdk: oraclejdk9
  - jdk: openjdk10
    dist: xenial
  - jdk: openjdk11
    dist: xenial
  - jdk: openjdk-ea
    branches:
      only:
      - master
    if: TRAVIS_PULL_REQUEST != false
  allow_failures:
  - jdk: openjdk11
  - jdk: openjdk-ea
  - name: "Flowable 5 tests"

cache:
  directories:
  - $HOME/.m2

notifications:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_script:
  - echo MAVEN_OPTS=\"-Xmx2048m -Xms1024m -Djava.awt.headless=true\" > ~/.mavenrc

script:
  mvn test -Pdistro,errorLogging -DskipTests=false -B
