version: '2'
services:
  flowable-rest-app:
    image: flowable/flowable-rest
    depends_on:
      - flowable-db
    environment:
      - datasource.driver=org.postgresql.Driver
      - datasource.url=jdbc:postgresql://flowable-db:5432/flowable
      - datasource.username=flowable
      - datasource.password=flowable
      - rest.docs.swagger.enabled=false
    expose:
      - "9977"
    entrypoint: ["./wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "java", "-jar", "flowable-rest.jar", "-httpPort=9977", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
  flowable-db:
      extends:
        file: postgres.yml
        service: flowable-postgres
  flowable-lb:
    image: dockercloud/haproxy
    links:
      - flowable-rest-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
      - 8081:1936
