version: '2'
services:
    flowable-postgres:
        container_name: flowable-postgres
        image: postgres:9.6-alpine
#         volumes:
#             - ~/flowable/flowable-modeler/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=flowable
            - POSTGRES_USER=flowable
            - POSTGRES_DB=flowable
        ports:
            - 5432:5432
        command: postgres
