{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowable.template" . }}
  labels:
    {{ include "flowable.defaultlabels" . }}
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flowable.template" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flowable.template" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        command: ['sh', '-c', 'until pg_isready -h {{ .Values.postgres.service.name }} -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
      - name: {{ include "flowable.template" . }}
        image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
        imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
        ports:
        - containerPort: 9988
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9988
            httpHeaders:
            - name: Authorization
              value: Basic YWRtaW46dGVzdA==
          initialDelaySeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9988
            httpHeaders:
            - name: Authorization
              value: Basic YWRtaW46dGVzdA==
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 10
        envFrom:
        - configMapRef:
            name: {{ include "flowable.template" . }}-configmap
        volumeMounts:
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
      restartPolicy: Always
      volumes:
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.service.name }}
  labels:
    {{ include "flowable.defaultlabels" . }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "flowable.template" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 9988
    targetPort: 9988
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flowable.template" . }}-configmap
data:
  JAVA_OPTS: "{{ .Values.admin.javaOpts }} -Djava.security.egd=file:/dev/./urandom"
  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.admin.contextUrl | quote }}
  SERVER_SERVLET_SESSION_TIMEOUT: 1h
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Values.postgres.service.name }}:5432/{{ .Values.flowable.database.name }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.flowable.database.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.flowable.database.password }}
  FLOWABLE_COMMON_APP_IDM-URL: http://{{ .Values.idm.service.name }}:8080
  FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://{{ .Values.flowable.host.external }}/flowable-idm/
  FLOWABLE_COMMON_APP_REDIRECT-ON-AUTH-SUCCESS: http://{{ .Values.flowable.host.external }}/flowable-admin/
  FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
  FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
  {{- if .Values.task.enabled }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS: http://{{ .Values.task.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT: process-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS: http://{{ .Values.task.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT: cmmn-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS: http://{{ .Values.task.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT: dmn-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS: http://{{ .Values.task.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT: form-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS: http://{{ .Values.task.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT: content-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS: http://{{ .Values.task.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT: app-api
  {{- else if .Values.rest.enabled }}}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS: http://{{ .Values.rest.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT: "8080"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT: process-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS: http://{{ .Values.rest.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT: "8080"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT: cmmn-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS: http://{{ .Values.rest.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT: "8080"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT: dmn-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS: http://{{ .Values.rest.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT: "8080"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT: form-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS: http://{{ .Values.rest.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT: "8080"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT: content-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS: http://{{ .Values.rest.service.name }}
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT: "8080"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT: /
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT: app-api
  {{- end }}
{{- end }}