{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ include "flowable.template" . }}
  labels:
    {{ include "flowable.defaultlabels" . }}
  annotations:
    # nginx.ingress.kubernetes.io/enable-access-log: "true"
    # nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    {{- if .Values.ui.enabled }}
    nginx.ingress.kubernetes.io/app-root: {{ .Values.ui.contextPath }}
    {{- end}}
    {{- if .Values.rest.enabled }}
    nginx.ingress.kubernetes.io/app-root: {{ .Values.rest.contextPath }}
    {{- end}}
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.clusterIssuer }}"
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.useHost }}
  - host: {{ .Values.host.external }}
    http:
      {{ include "flowable.ingressRules" . }}
  {{- else }}
  - http:
      {{ include "flowable.ingressRules" . }}
  {{- end }}
  {{- if .Values.ingress.clusterIssuer }}
  tls:
  - hosts:
    - {{ .Values.host.external }}
    secretName: {{ .Values.ingress.secretName | default "flowable-tls" }}
  {{- end }}
{{- end }}
