version: '2'
services:
    flowable-modeler-app:
        image: flowable/flowable-modeler
        depends_on:
            - flowable-modeler-db
            - flowable-idm-app
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://flowable-modeler-db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
            - flowable.app.idm.url=http://flowable-idm-app:8080/flowable-idm
            - flowable.app.idm.admin.user=admin
            - flowable.app.idm.admin.password=test
        ports:
            - 8888:8888
        entrypoint: ["./wait-for-something.sh", "flowable-modeler-db", "5432", "PostgreSQL", "java", "-jar", "flowable-modeler.jar", "-httpPort=8888", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-idm-app:
        image: flowable/flowable-idm
        depends_on:
            - flowable-modeler-db
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://flowable-modeler-db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-modeler-db", "5432", "PostgreSQL", "java", "-jar", "flowable-idm.jar", "-httpPort=8080", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-modeler-db:
        extends:
            file: postgres.yml
            service: flowable-modeler-postgres
