host:
  # Public / external hostname (f.e. LB)
  external: localhost
# Global database name, user and password
database:
  name: flowable
  username: flowable
  password: flowable
  # specify to overwrite dynamic template values 
  # datasourceDriverClassName:
  # datasourceUrl:
cloudSql:
  enabled: false
  # Google Cloud SQL instance connection name
  # instanceConnectionName: 
  # Google credentials file name stored as secret in the cluster
  credentials: cloudsql-credentials.json

ingress:
  enabled: true
  sslRedirect: false
  useHost: false
  class: "nginx"
  # To enable LetsEncrypt signed certificates rather than self-signed ones
  # you must deploy a ClusterIssuer object and specify the privateKeySecretRef's
  # name here
  #clusterIssuer: "letsencrypt-prod"

# Enable either Flowable UI or Flowable REST
ui:
  enabled: true
  replicas: 1
  service:
    name: flowable-ui
  contextPath: /flowable-ui
  ingressPath: /
  image:
    repository: flowable/flowable-ui
    tag: 6.7.0
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  javaOpts: "-Xmx1g -Xms1g"
  admin:
    username: admin
    password: test
  idm:
    admin:
      username: admin
      password: test

# Enable either Flowable UI or Flowable REST
rest:
  enabled: false
  replicas: 1
  service:
    name: flowable-rest
  contextPath: /flowable-rest
  ingressPath: /
  image:
    repository: flowable/flowable-rest
    tag: 6.7.0
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  javaOpts: "-Xmx1g -Xms1g"
  admin:
    username: rest-admin
    password: test

postgres:
  enabled: true
  service:
    name: flowable-postgres
  image: postgres:9.6
  storage:
    storageClassName: "standard"
#    storageClassName: "ssd"
    size: 1Gi
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
