apiVersion: v1
entries:
  flowable:
  - apiVersion: v2
    appVersion: 6.7.2
    created: "2022-01-05T18:02:23.127923+01:00"
    description: A Flowable Helm chart for Kubernetes
    digest: 38c7817a7246775add219caf7d333fb701bbfa5ac56acd7da8d445466f6f8eb4
    home: https://flowable.org
    icon: https://flowable.org/docs/img/logo.png
    name: flowable
    urls:
    - https://flowable.github.io/helm/flowable-6.7.3-snapshot.1.tgz
    version: 6.7.3-snapshot.1
  - apiVersion: v2
    appVersion: 6.7.2
    created: "2021-12-28T16:23:36.018661+01:00"
    description: A Flowable Helm chart for Kubernetes
    digest: fee57c7bc131f48b1773dee1022183afd9695b72e6dc8e632ba08d7653ff62b1
    home: https://flowable.org
    icon: https://flowable.org/docs/img/logo.png
    name: flowable
    urls:
    - https://flowable.github.io/helm/flowable-6.7.2.tgz
    version: 6.7.2
  - apiVersion: v2
    appVersion: 6.7.1
    created: "2021-11-15T17:08:47.903154+01:00"
    description: A Flowable Helm chart for Kubernetes
    digest: 1c7348cb60f72fb5d0855ad18e1f1ccc9ac037925359b615ad1581cbb6ecb27d
    home: https://flowable.org
    icon: https://flowable.org/docs/img/logo.png
    name: flowable
    urls:
    - https://flowable.github.io/helm/flowable-6.7.1.tgz
    version: 6.7.1
  - apiVersion: v2
    appVersion: 6.7.0
    created: "2021-11-15T17:08:47.902329+01:00"
    description: A Flowable Helm chart for Kubernetes
    digest: 625ffc2c80e9cffa00feaffcdd00c17414e756a7a22a30fffb5c14443beb8ac9
    home: https://flowable.org
    icon: https://flowable.org/docs/img/logo.png
    name: flowable
    urls:
    - https://flowable.github.io/helm/flowable-6.7.0.tgz
    version: 6.7.0
  - apiVersion: v1
    appVersion: 6.6.0
    created: "2021-11-15T17:08:47.901538+01:00"
    dependencies:
    - condition: nginx-ingress.enabled
      name: nginx-ingress
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.3.1
    description: A Flowable Helm chart for Kubernetes
    digest: 80be137a64d743cc1e0948009f51ed4861ef3dfd2f39d8baecc5ad0cebe89354
    home: https://flowable.org
    icon: https://flowable.org/docs/img/logo.png
    name: flowable
    urls:
    - https://flowable.github.io/helm/flowable-6.6.0.tgz
    version: 6.6.0
  - apiVersion: v1
    appVersion: 6.5.0
    created: "2021-11-15T17:08:47.899381+01:00"
    dependencies:
    - condition: nginx-ingress.enabled
      name: nginx-ingress
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.3.1
    description: A Flowable Helm chart for Kubernetes
    digest: d231d0b5ba78c6f0952ba2ab5ed0b17566f54a46af3ad840107690715a782f61
    home: https://flowable.org
    icon: https://flowable.org/docs/img/logo.png
    name: flowable
    urls:
    - https://flowable.github.io/helm/flowable-6.5.0.tgz
    version: 6.5.0
generated: "2022-01-05T18:02:23.123701+01:00"
