version: '2'
services:
    flowable-task-app:
        image: flowable/flowable-task
        depends_on:
            - flowable-task-db
            - flowable-idm-app
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://flowable-task-db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
            - flowable.app.idm.url=http://flowable-idm-app:8080/flowable-idm
            - flowable.app.idm.admin.user=admin
            - flowable.app.idm.admin.password=test
        ports:
            - 9999:9999
        entrypoint: ["./wait-for-something.sh", "flowable-task-db", "5432", "PostgreSQL", "java", "-jar", "flowable-task.jar", "-httpPort=9999", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-idm-app:
        image: flowable/flowable-idm
        depends_on:
            - flowable-task-db
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://flowable-task-db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-task-db", "5432", "PostgreSQL", "java", "-jar", "flowable-idm.jar", "-httpPort=8080", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-task-db:
        extends:
            file: postgres.yml
            service: flowable-task-postgres
