version: '2'
services:
    flowable-admin-app:
        image: flowable/flowable-admin
        depends_on:
            - flowable-admin-db
            - flowable-idm-app
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://flowable-admin-db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
            - flowable.app.idm.url=http://flowable-idm-app:8080/flowable-idm
            - flowable.app.idm.admin.user=admin
            - flowable.app.idm.admin.password=test
        ports:
            - 9988:9988
        entrypoint: ["./wait-for-something.sh", "flowable-admin-db", "5432", "PostgreSQL", "java", "-jar", "flowable-admin.jar", "-httpPort=9988", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-idm-app:
        image: flowable/flowable-idm
        depends_on:
            - flowable-admin-db
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://flowable-admin-db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-admin-db", "5432", "PostgreSQL", "java", "-jar", "flowable-idm.jar", "-httpPort=8080", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-admin-db:
        extends:
            file: postgres.yml
            service: flowable-admin-postgres
