name: Flowable Async History Build

on: [push]

env:
  MAVEN_ARGS: >-
    -Dmaven.javadoc.skip=true
    -B -V --no-transfer-progress
    -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  test_async:
    name: Async History ${{ matrix.engineModule }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        engineModule: ['flowable-engine', 'flowable-cmmn-engine']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install
        run: >-
          ./mvnw clean install
          -Dmaven.javadoc.skip=true -B -V --no-transfer-progress
          -DskipTests
      - name: Test
        run: >-
          ./mvnw test
          ${MAVEN_ARGS}
          -Pcfghistoryasync
          -pl org.flowable:${{ matrix.engineModule }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/*'