name: Flowable MySQL Build

on:
  push:
    branches:
      - master
      - 'flowable-release-*'

# We explicitly don't use a container for running the job since there is some connectivity issues to MySQL if that is done
jobs:
  test_mysql:
    name: MySQL ${{ matrix.mysql }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql: [5.7, 8]
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_DATABASE: flowable
          MYSQL_USER: flowable
          MYSQL_PASSWORD: flowable
          MYSQL_ROOT_PASSWORD: flowable
        ports:
          - 3306/tcp
        # needed because the mysql container does not provide a health check
        options: --health-cmd="mysqladmin -uflowable -pflowable status" --health-interval 10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 10
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        # use localhost for the host here because we have specified a vm for the job.
        # '>-' is a special YAML syntax and means that new lines would be replaced with spaces
        # and new lines from the end would be removed
        run: >-
          ./mvnw clean install
          -Dmaven.javadoc.skip=true -B -V
          -PcleanDb,mysql
          -Djdbc.url=jdbc:mysql://localhost:${{ job.services.mysql.ports[3306] }}/flowable?characterEncoding=UTF-8
          -Djdbc.username=flowable
          -Djdbc.password=flowable
          -Djdbc.driver=com.mysql.cj.jdbc.Driver
          -Dmaven.test.redirectTestOutputToFile=false
  test_mysql_dmn:
    name: MySQL ${{ matrix.mysql }} DMN
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql: [5.7, 8]
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_DATABASE: flowable
          MYSQL_USER: flowable
          MYSQL_PASSWORD: flowable
          MYSQL_ROOT_PASSWORD: flowable
        ports:
          - 3306/tcp
        # needed because the mysql container does not provide a health check
        options: --health-cmd="mysqladmin -uflowable -pflowable status" --health-interval 10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 10
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        # use mysql for the host here because we have specified a container for the job.
        # '>-' is a special YAML syntax and means that new lines would be replaced with spaces
        # and new lines from the end would be removed
        run: >-
          ./mvnw clean install
          -Dmaven.javadoc.skip=true -B -V
          -Pdmn,mysql
          -Djdbc.url=jdbc:mysql://localhost:${{ job.services.mysql.ports[3306] }}/flowable?characterEncoding=UTF-8
          -Djdbc.username=flowable
          -Djdbc.password=flowable
          -Djdbc.driver=com.mysql.cj.jdbc.Driver
          -Dmaven.test.redirectTestOutputToFile=false
          -pl org.flowable:flowable-dmn-engine -am
  test_mysql_content:
    name: MySQL ${{ matrix.mysql }} Content
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql: [5.7, 8]
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_DATABASE: flowable
          MYSQL_USER: flowable
          MYSQL_PASSWORD: flowable
          MYSQL_ROOT_PASSWORD: flowable
        ports:
          - 3306/tcp
        # needed because the mysql container does not provide a health check
        options: --health-cmd="mysqladmin -uflowable -pflowable status" --health-interval 10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 10
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        # use localhost for the host here because we have specified a vm for the job.
        # '>-' is a special YAML syntax and means that new lines would be replaced with spaces
        # and new lines from the end would be removed
        run: >-
          ./mvnw clean install
          -Dmaven.javadoc.skip=true -B -V
          -Pcontent,mysql
          -Djdbc.url=jdbc:mysql://localhost:${{ job.services.mysql.ports[3306] }}/flowable?characterEncoding=UTF-8
          -Djdbc.username=flowable
          -Djdbc.password=flowable
          -Djdbc.driver=com.mysql.cj.jdbc.Driver
          -Dmaven.test.redirectTestOutputToFile=false
          -pl org.flowable:flowable-content-engine -am
